# Generated by Django 3.2.7 on 2022-01-31 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Club Name')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('home_goals', models.IntegerField(default=0)),
                ('away_goals', models.IntegerField(default=0)),
                ('result', models.CharField(choices=[('l', 'Lose'), ('d', 'Draw'), ('w', 'Win')], default='d', max_length=2)),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='main.club')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='main.club')),
            ],
        ),
    ]
